version: '3.5'

services:
  mongodev:
    container_name: mongodev
    image: mongo
    ports:
      - "27017:27017"
    networks:
        - sajadweb
    expose:
      - 27017
    restart: always
    volumes:
      - db_mongo:/data/db:rw

networks:
  sajadweb:
    external: true

volumes:
  db_mongo: {}