version: '3.5'

services:
  mongodev:
    container_name: mongodev
    image: mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    expose:
      - 27017
    env_file:
      - docker.env
    volumes:
      - db_mongo:/data/db:rw
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./config/mongo.conf:/etc/mongo/mongo.conf:ro
      # - ./mongo-keyfile:/etc/mongo/mongo-keyfile:ro
    command:  >
      bash -c "
      if [ ! -f /mongodb-keyfile ]; then
        openssl rand -base64 756 > /mongodb-keyfile
        chmod 600 /mongodb-keyfile
        chown mongodb:mongodb /mongodb-keyfile
      fi
      exec mongod --config /etc/mongo.conf --keyFile /mongodb-keyfile --bind_ip_all
      "
    networks:
      - sajadweb


networks:
  sajadweb:
    external: true

volumes:
  db_mongo: {}