version: "3.5"

services:
  #Redis Service
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: redis
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - db_redis:/data:rw
    # command: "redis-server --requirepass 123456"
    networks:
      - sajadweb
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      # - REDIS_HOSTS=local:redis:6379:2:123456
    ports:
      - "6380:8081"
    depends_on:
        - redis
    networks:
      - sajadweb
networks:
  sajadweb:
    external: true

volumes:
  db_redis: {}
