version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysqldev
    volumes:
      - db_mysql:/var/lib/mysql:rw
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
        - sajadweb
    env_file:
    - docker.env

  mongodev:
    container_name: mongodev
    image: mongo
    ports:
      - "27017:27017"
    networks:
        - sajadweb
    expose:
      - 27017
    restart: always
    volumes:
      - db_mongo:/data/db:rw
  postgres:
    image: postgres:12-alpine
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
        - sajadweb
    expose:
      - 5432
    env_file:
    - docker.env
    volumes:
      - db_post:/var/lib/postgresql/data:rw
  #Redis Service
  redis:
    image: redis:6-alpine
    container_name: redis
    expose:
      - 6379
    volumes:
        - db_redis:/data:rw 
    ports:
      - "6379:6379"
    networks:
        - sajadweb
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 90:8080
    expose:
      - 90
    networks:
        - sajadweb
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "110:80"
    expose:
      - 110
    volumes:
    - db_pgadmin:/root/.pgadmin:rw
    env_file:
    - docker.env
    networks:
        - sajadweb

networks:
  sajadweb:
    external: true

volumes:
  db_mysql: {}
  db_mongo: {}
  db_post: {}
  db_redis: {}
  db_pgadmin: {}