version: "3.5"

services:
  #Redis Service
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: redis
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - db_redis:/data:rw
    networks:
      - sajadweb

networks:
  sajadweb:
    external: true

volumes:
  db_redis: {}
