version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
     - docker.env
    volumes:
      - db_post:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - sajadweb
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - docker.env
    volumes:
      - db_pgadmin:/root/.pgadmin:rw
    ports:
      - "5050:80"
    networks:
      - sajadweb
    restart: unless-stopped
 
  #Redis Service
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
        - db_redis:/data:rw
    networks:
        - sajadweb
networks:
  sajadweb:
    external: true

volumes:
  db_post: {}
  db_redis: {}
  db_pgadmin: {}